name: macos

on: [push, pull_request]

jobs:

  macos-build:
    runs-on: ${{ matrix.macos-version }}
    strategy:
      fail-fast: false
      matrix:
        macos-version:
          - 'macos-latest'

    steps:
      - name: Sync repository
        uses: actions/checkout@v2

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1  # not v2!
        with:
          path: '${{ github.workspace }}/qt_installation/'
          key: ${{ runner.os }}-QtCache

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install deps
        run: brew install cmake qt@5 protobuf mosquitto zeromq zstd zmqpp

      - name: Build Plotjuggler
        shell: bash
        run: >
          QT_HOME=$(brew --prefix qt@5)
          export CPPFLAGS="-I $QT_HOME/include";
          export PKG_CONFIG_PATH="$QT_HOME/lib/pkgconfig";
          cmake -B build/PlotJuggler -DCMAKE_INSTALL_PREFIX=install -DCMAKE_OSX_ARCHITECTURES="arm64"
          cmake --build build/PlotJuggler --config RelWithDebInfo --target install 2>&1 |tee log
